# Generated by Django 5.2.8 on 2025-11-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('secret_number', models.IntegerField()),
                ('attempts', models.IntegerField(default=0)),
                ('is_won', models.BooleanField(default=False)),
            ],
        ),
    ]
